[[HelloWorldC2]]
arch = "i686"
git-tree-sha1 = "987df6ceac1563dfda71f36feda97c4f2c9ad52c"
libc = "glibc"
os = "linux"

    [[HelloWorldC2.download]]
    sha256 = "a2d55a18caa3c7c16d9372b438e8dfbfb91577af3950c174dd9e0815b575c76b"
    url = "https://github.com/EnzymeAD/HelloWorldC2_jll.jl/releases/download/HelloWorldC2-v1.0.0+0/HelloWorldC2.v1.0.0.i686-linux-gnu.tar.xz"
[[HelloWorldC2]]
arch = "x86_64"
git-tree-sha1 = "22c00fd8908a6e2d727687709393787d8f499c8f"
libc = "glibc"
os = "linux"

    [[HelloWorldC2.download]]
    sha256 = "9fa01c84a26654dce9cafed9aeefbb8d5165cfd2b56949be6ea91f5795fc2ceb"
    url = "https://github.com/EnzymeAD/HelloWorldC2_jll.jl/releases/download/HelloWorldC2-v1.0.0+0/HelloWorldC2.v1.0.0.x86_64-linux-gnu.tar.xz"
